services:
  hello-java:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    image: hello-java:latest  # 构建后镜像的名称和标签，建议和项目绑定，否则和其他项目冲突
    restart: unless-stopped # 重启策略
    environment:
      APP_NAME: "hello-java"
      # -- mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: default_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my_secret_password
      # -- nvidia-docker
      # NVIDIA_VISIBLE_DEVICES: all
      # NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - ".:/root/hello-java"
      - "~/.ssh:/root/.ssh:ro" # 挂载宿主机的ssh配置文件，方便推拉代码（只读）
      - "/etc/localtime:/etc/localtime:ro" # 挂载宿主机时间到容器
    working_dir: /root/hello-java
    networks:
      - default
    # -- 端口映射 (宿主机端口:容器端口)
    ports:          
      - "18080:8080"
      - "18081:8081"
      - "18082:8082"
    command: ["sleep", 'infinity']

  # MySQL
  mysql-server:
    image: mysql:9 # https://hub.docker.com/_/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root_secret_password}
      MYSQL_DATABASE: default_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: my_secret_password
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql  # 初始化数据库脚本
      # - ./sql/mysql/sql:/opt/sql  # 初始化数据库脚本

  # Redis
  redis-server:
    image: redis:7 # https://hub.docker.com/_/redis
    ports:
      - "6379:6379"
    networks:
      - default
      
# -- 网络名称，用于容器间通信
networks:
  default:
    name: hello-docker-network
  

# -- 数据卷名称，用于持久化数据
volumes:
  mysql_data: