
spring:  
    application:
        name: hello-java
    jpa:
        hibernate:
            # 更新或者创建数据表结构
            ddl-auto: update
            # 控制台显示SQL
            show-sql: true
    datasource:
        url: jdbc:mysql://mysql-server:3306/default_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: myuser
        password: my_secret_password
        driver-class-name: com.mysql.cj.jdbc.Driver